# Generated by Django 3.0.6 on 2020-06-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
